# Numpy Package

In [5]:
# Added the header to notebood with our new markdown skills!

In [1]:
import numpy # whenever we want to use a package, the 1st this we do is importing it to python! 

In [4]:
numpy? #note, you can also type help(numpy) to get the same help docstring below the cell directly. 

In [6]:
import numpy as np # This creates an alias. If you want any function of numpy (e.g. "random" = np.random)
# if you dont say import numpy as np, you would need to type numpy.random. Giving it "np" alias will just allow you to use it more easily. 

### numpy data structures: arrays

In [10]:
# np.random.random # This tells you the CLASS and the LEVEL of the function. 

In [12]:
np.random.random((2,3)) 

# the first () calls the function, the second () tells it the format we want it to take. In this case, a 2 by 3 matrix!
# Created a random array of numbers between 0 and 1, in 2,3 matrix. 

array([[0.28482144, 0.06162293, 0.43166002],
       [0.04702648, 0.82138925, 0.48377635]])

In [17]:
a = np.random.random((2,3))
print(a)

# Note: your a and your first randomly generated matrix are different because because when you defined a, it was a 
# different randomly generated matrix than the first one. To reassign a, you would just re-generate a new random matrix. 

[[0.93980728 0.11986722 0.96074541]
 [0.76355274 0.54693792 0.40412314]]


In [33]:
a.shape # Note: if you are defining the shape of the matrix, you will define the shape as a tuple. e.g. (2,3)

(2, 3)

In [19]:
a.size # tells us how many items are in our matrix; (2*3) in this case

6

### Extracting data from arrays

In [20]:
a[0,0] # This is to call the element at the top left corner! 0th index of the rows and 0th index of the column! 

0.9398072809313405

In [21]:
a[0,1] # row 0, column 1

0.11986722336523126

In [22]:
a[1,2] # gives us the bottom right corner!

0.40412314225367296

In [23]:
a[0] # This gives you the entire first ROW! You could also write a[0,:] like in the example below

array([0.93980728, 0.11986722, 0.96074541])

In [24]:
a[:,0] # This is how you get the first COLUMN. 

array([0.93980728, 0.76355274])

In [25]:
b = np.random.random((2,3,5)) # FIRST PARAMETER IS THE DEPTH, then you have 3 rows, 5 columns).
print(b)

[[[0.03456262 0.92197318 0.61704256 0.37016615 0.50907234]
  [0.16235438 0.20635236 0.57238836 0.04897172 0.88111422]
  [0.20426714 0.82352231 0.02528451 0.8644727  0.45806525]]

 [[0.49000459 0.5791282  0.73993496 0.31939253 0.53333931]
  [0.11380851 0.22461694 0.64898571 0.77192464 0.38818627]
  [0.82711957 0.88348986 0.20803476 0.40780611 0.26173143]]]


In [26]:
b.size # 2 * 3 * 5

30

In [27]:
b[0,0,0] # calls the top left element! 

0.034562619909975445

In [28]:
b[0,2,:] # This gives you the ENTIRE last (3rd row, index 2) ROW of the first matrix in the third dimension. 

array([0.20426714, 0.82352231, 0.02528451, 0.8644727 , 0.45806525])

In [30]:
b[0,0,0] = 5
b 
# This shows that arrays are MUTABLE. It allows you to reassign specific values. 

array([[[5.        , 0.92197318, 0.61704256, 0.37016615, 0.50907234],
        [0.16235438, 0.20635236, 0.57238836, 0.04897172, 0.88111422],
        [0.20426714, 0.82352231, 0.02528451, 0.8644727 , 0.45806525]],

       [[0.49000459, 0.5791282 , 0.73993496, 0.31939253, 0.53333931],
        [0.11380851, 0.22461694, 0.64898571, 0.77192464, 0.38818627],
        [0.82711957, 0.88348986, 0.20803476, 0.40780611, 0.26173143]]])

### Converting other data structures to arrays

In [34]:
# mylist = ['cat', 'dog']
mylist = [['cat', 'dog'], ['squirrel', 'mouse'], ['anteater', 'bear']]

In [35]:
np.array(mylist)

array([['cat', 'dog'],
       ['squirrel', 'mouse'],
       ['anteater', 'bear']], dtype='<U8')

### Element-wise mathematical operations