# Numpy Package

In [1]:
# Added the header to notebood with our new markdown skills!

In [6]:
import numpy # whenever we want to use a package, the 1st this we do is importing it to python! 

In [7]:
numpy? #note, you can also type help(numpy) to get the same help docstring below the cell directly. 

SyntaxError: invalid syntax (<ipython-input-7-69d9dc427e4f>, line 1)

In [8]:
import numpy as np # This creates an alias. If you want any function of numpy (e.g. "random" = np.random)
# if you dont say import numpy as np, you would need to type numpy.random. Giving it "np" alias will just allow you to use it more easily. 

### numpy data structures: arrays

In [9]:
# np.random.random # This tells you the CLASS and the LEVEL of the function. 

In [10]:
np.random.random((2,3)) 

# the first () calls the function, the second () tells it the format we want it to take. In this case, a 2 by 3 matrix!
# Created a random array of numbers between 0 and 1, in 2,3 matrix. 

array([[0.3199535 , 0.49436701, 0.70008302],
       [0.08878545, 0.37360308, 0.06422368]])

In [11]:
a = np.random.random((2,3))
print(a)

# Note: your a and your first randomly generated matrix are different because because when you defined a, it was a 
# different randomly generated matrix than the first one. To reassign a, you would just re-generate a new random matrix. 

[[0.37024017 0.8028154  0.63938603]
 [0.34062743 0.81028808 0.86048606]]


In [12]:
a.shape # Note: if you are defining the shape of the matrix, you will define the shape as a tuple. e.g. (2,3)

(2, 3)

In [13]:
a.size # tells us how many items are in our matrix; (2*3) in this case

6

### Extracting data from arrays

In [14]:
a[0,0] # This is to call the element at the top left corner! 0th index of the rows and 0th index of the column! 

0.37024016856423236

In [15]:
a[0,1] # row 0, column 1

0.8028153971991363

In [16]:
a[1,2] # gives us the bottom right corner!

0.8604860613964241

In [17]:
a[0] # This gives you the entire first ROW! You could also write a[0,:] like in the example below

array([0.37024017, 0.8028154 , 0.63938603])

In [18]:
a[:,0] # This is how you get the first COLUMN. 

array([0.37024017, 0.34062743])

In [19]:
b = np.random.random((2,3,5)) # FIRST PARAMETER IS THE DEPTH, then you have 3 rows, 5 columns).
print(b)

[[[0.42522988 0.60824414 0.63197947 0.0595478  0.03039293]
  [0.61158504 0.94109653 0.19228839 0.32122996 0.54447662]
  [0.87192157 0.2568944  0.8705265  0.39197224 0.57211342]]

 [[0.96387545 0.91095884 0.88458882 0.10636152 0.03619335]
  [0.48818352 0.31591027 0.92174814 0.00723006 0.6890836 ]
  [0.75695595 0.26924047 0.26828411 0.49930333 0.42129046]]]


In [20]:
b.size # 2 * 3 * 5

30

In [21]:
b[0,0,0] # calls the top left element! 

0.4252298795216969

In [22]:
b[0,2,:] # This gives you the ENTIRE last (3rd row, index 2) ROW of the first matrix in the third dimension. 

array([0.87192157, 0.2568944 , 0.8705265 , 0.39197224, 0.57211342])

In [23]:
b[0,0,0] = 5
b 
# This shows that arrays are MUTABLE. It allows you to reassign specific values. 

array([[[5.        , 0.60824414, 0.63197947, 0.0595478 , 0.03039293],
        [0.61158504, 0.94109653, 0.19228839, 0.32122996, 0.54447662],
        [0.87192157, 0.2568944 , 0.8705265 , 0.39197224, 0.57211342]],

       [[0.96387545, 0.91095884, 0.88458882, 0.10636152, 0.03619335],
        [0.48818352, 0.31591027, 0.92174814, 0.00723006, 0.6890836 ],
        [0.75695595, 0.26924047, 0.26828411, 0.49930333, 0.42129046]]])

### Converting other data structures to arrays

In [24]:
# mylist = ['cat', 'dog']
mylist = [['cat', 'dog'], ['squirrel', 'mouse'], ['anteater', 'bear']]

In [25]:
np.array(mylist)

array([['cat', 'dog'],
       ['squirrel', 'mouse'],
       ['anteater', 'bear']], dtype='<U8')

### Element-wise mathematical operations

In [28]:
first = np.random.random((3,4)) # first random is the CLASS, the second random is a FUNCTION. 
second = np.random.random((3,4))
print(first)
print(second)

[[0.05817358 0.57421568 0.81578991 0.66791606]
 [0.3426523  0.4467405  0.18590737 0.86933968]
 [0.12884526 0.71440432 0.18267037 0.76958399]]
[[0.03704006 0.9614494  0.37631257 0.90623283]
 [0.83585717 0.01233529 0.92298605 0.2866711 ]
 [0.69525212 0.40036275 0.3890359  0.61056077]]


In [27]:
10*first # if you want a matrix of random numbers between 0 and TEN instead of the randomly generated  range 0-1, then just multiply the matrix by 10


array([[6.51653386, 5.4693698 , 9.73137744, 2.13731812],
       [8.52091045, 5.56913489, 1.83134625, 5.79007216],
       [0.50030233, 7.36596766, 9.11180563, 7.16348944]])

In [30]:
sum1 = np.add(first,second)
print(sum1)

# if your matrices are different dimensions, you cant add them

[[0.09521363 1.53566508 1.19210247 1.57414889]
 [1.17850947 0.45907579 1.10889342 1.15601078]
 [0.82409739 1.11476707 0.57170628 1.38014476]]


In [31]:
first + second # this also works! 

array([[0.09521363, 1.53566508, 1.19210247, 1.57414889],
       [1.17850947, 0.45907579, 1.10889342, 1.15601078],
       [0.82409739, 1.11476707, 0.57170628, 1.38014476]])

In [32]:
[1, 2, 4] + [1, 2, 3] # This just combines the lists rather than doing element-wise addition 

[1, 2, 4, 1, 2, 3]

In [33]:
np.add([1, 2, 4],[1, 2, 3]) # This is why sometimes using np.add is sometimes smarter than just pyhton mathematical operators

# notice the difference between this result and the result in the cell above

array([2, 4, 7])