# Working with Numpy

Numpy is the numerical python package, with a lot of mathematical capabilities. Before we can use it, we need to first import the package. We will import it under the name np such that we can afterwards refer to it by this short name.

In [1]:
import numpy as np

In the cell below, generate two 2x3 array with all elements equal to 1 - assign one of the arrays to the variable a and the other one to b. Add the two arrays. What do you get?

In [12]:
a = np.full((2,3), 1) # Generate arrays with all elements = to 1
b = np.full((2,3), 1)

result = np.add(a,b)
print(result)

# each element of array a was added to each identical element in array b

[[2 2 2]
 [2 2 2]]


Now generate another array c which is a 3x2 array with all elements equal to 1. Are you able to add a and c? Why or why not?

In [16]:
c = np.full((3,2), 1)
print(c)

np.add(a,c) 
# This won't work because the dimensions of a and c are not the same

[[1 1]
 [1 1]
 [1 1]]


ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

Transpose c so that it has the same structure of a (i.e. become a 2x3 array). Assign the transposed array to variable "d". Are you able to add a and d?

In [32]:
d = np.transpose(c) # np.transpose() is a function I found online
print(d)

print(np.add(a,d)) # Now this will work because a and d have the same shape

[[1 1 1]
 [1 1 1]]
[[2 2 2]
 [2 2 2]]


Which combination of arrays are you able to multiply with each other? Why?

In [28]:
# we should be able to multiply a, b, and d but not c because c has a different shape than the other 3

np.multiply(a,b)
np.multiply(a,d)
np.multiply(b,d)
# np.multply(a,c) Would give you the error

array([[1, 1, 1],
       [1, 1, 1]])

Create a list which contains the numbers from 0 to 10. Square the list elementwise using numpy functions.

In [34]:
list = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

# square the list elementwise using numpy functions

squared_list = np.array(list) ** 2
print(squared_list) # Note that with the print function, there will be NO commas between elements. If I just call the array w/out print functino, there will be ommas.

[  0   1   4   9  16  25  36  49  64  81 100]


Create a numpy array of size 10x10 which has random numbers between 0 and 100 on the main diagonal and zeros otherwise.

In [59]:
array1 = np.full((10,10), 0)

np.fill_diagonal(array1,1)
print(array1)

x = np.random.random((10,10))
print(x)

result = array1 * (x*100)
print(result)


# NOTE: there is a numpy function for an identity matrix (which has 1 on the diagonal and zero everywhere else!)

# you can generate an array with random # from 0 to 100 and MULTIPLY it by an identity matrix, because only the 1s change if multiplied

[[1 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 1]]
[[0.95448693 0.50626755 0.07809648 0.50614051 0.72771652 0.77918685
  0.54736245 0.64847183 0.25788859 0.00385945]
 [0.06604196 0.77532914 0.22802285 0.11329636 0.5290534  0.00151918
  0.41460499 0.57724335 0.94071677 0.16144809]
 [0.61817119 0.08790503 0.99366757 0.77214646 0.04900249 0.92132639
  0.34934499 0.4651236  0.99023446 0.77320968]
 [0.65921607 0.95651647 0.44759513 0.23915334 0.85201024 0.26659818
  0.29667263 0.66542379 0.80407433 0.09544535]
 [0.68873629 0.55707637 0.62138205 0.36099956 0.50734673 0.47641637
  0.0453901  0.41763613 0.25346138 0.99796073]
 [0.86186836 0.13899277 0.1291285  0.43119664 0.34189004 0.00465004
  0.57050116 0.17710631 0.40284154 0.79564035]
 [0.52074073 0.47109398 0.53396574 0.48228646 0.38296427 0.13945838
  0.7762207